export const defaultPermissionsByRole: Record<string, string[]> = {
  superadmin: ["*"],
  tenant_admin: ["*"],
  manager: [
    "access.dashboard",
    "access.alerts",
    "products.view",
    "products.add",
    "products.duplicate",
    "products.edit",
    "products.delete",
    "products.import_export",
    "inventory.view",
    "inventory.adjust_stock",
    "sales.view",
    "sales.create",
    "sales.edit",
    "invoices.view",
    "invoices.download_print",
    "invoices.export",
    "customers.view",
    "customers.add",
    "customers.edit",
    "customers.import_export",
    "customers.view_history",
    "hr.view",
    "reports.view",
    "reports.export",
    "logs.view",
    "settings.view_business",
    // "settings.edit_business", // Removed from manager defaults as per security update
    "settings.manage_notifications",
    "settings.manage_appearance",
    "settings.change_password",
  ],
  staff: [
    "access.dashboard",
    "access.alerts",
    "products.view",
    "inventory.view",
    "sales.view",
    "sales.create",
    "invoices.view",
    "invoices.download_print",
    "customers.view",
    "customers.add",
    "customers.edit",
    "settings.change_password",
  ],
  viewer: [
    "access.dashboard",
    "access.alerts",
    "products.view",
    "inventory.view",
    "sales.view",
    "invoices.view",
    "customers.view",
    "reports.view",
    "settings.view_business",
  ],
};
