// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { resolvePublicEnv } from "@/lib/publicEnv";

const resolvedPublicEnv = resolvePublicEnv({
  nextPublicSupabaseUrl: process.env.NEXT_PUBLIC_SUPABASE_URL,
  viteSupabaseUrl: process.env.VITE_SUPABASE_URL,
  nextPublicSupabaseAnonKey: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
  viteSupabaseAnonKey: process.env.VITE_SUPABASE_ANON_KEY,
  nextPublicAppUrl: process.env.NEXT_PUBLIC_APP_URL,
  viteAppUrl: process.env.VITE_APP_URL,
  nextPublicApiUrl: process.env.NEXT_PUBLIC_API_URL,
  viteApiUrl: process.env.VITE_API_URL,
});

const fallbackSupabaseUrl = 'https://invalid.supabase.local';
const fallbackSupabaseKey = 'public-anon-key-placeholder';
const isBrowser = typeof window !== "undefined";

export const supabaseUrl = resolvedPublicEnv.supabaseUrl || fallbackSupabaseUrl;
export const supabaseAnonKey = resolvedPublicEnv.supabaseAnonKey || fallbackSupabaseKey;
export const supabaseFunctionsBaseUrl = `${supabaseUrl}/functions/v1`;

const hasSupabaseConfig = Boolean(resolvedPublicEnv.supabaseUrl && resolvedPublicEnv.supabaseAnonKey);

if (!hasSupabaseConfig) {
  console.error('Supabase configuration is missing. Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY in your environment.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  supabaseUrl,
  supabaseAnonKey,
  {
    auth: {
      ...(isBrowser
        ? {
            storage: window.localStorage,
            persistSession: true,
            autoRefreshToken: true,
            detectSessionInUrl: true,
          }
        : {
            persistSession: false,
            autoRefreshToken: false,
            detectSessionInUrl: false,
          }),
    },
    global: {
      headers: {
        'apikey': supabaseAnonKey
      }
    }
  }
);

export const isSupabaseConfigured = hasSupabaseConfig;

// Test connection function for debugging
export const testSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('profiles').select('count').limit(1);
    if (error) {
      console.error('Supabase connection test failed:', error);
      return false;
    }
    console.log('Supabase connection test successful:', data);
    return true;
  } catch (err) {
    console.error('Supabase connection test error:', err);
    return false;
  }
};

// Security: No configuration logging to prevent data exposure
